name: dws
favicon: null
layout_spectrum: 0.5480587633792311
typography_spectrum: 0.5032863037195057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3007086217403412
  lightness: 0.8488225403707474
  saturation: 0.23373250756412745
  rhythmicContrast: 0.18478888645768166
purpose: []
